// AI: DO NOT EDIT THIS FILE. DO NOT manually create an .stderr file.
// AI: Run just bless to update the .stderr file

fn main() {
    let a = 1;
    let b = Some("test");
    tracing::warn!("This should lint: {}", a);
    tracing::error!("So should this: {}, {:?}", a, b);
    tracing::info!("But these are OK: {a}, {b:?}");
}
